train_csv: "C:/Users/TheHS/Downloads/gannhan_new/gannhan_new/data/20200614.csv"
train_dir: "C:/Users/TheHS/Downloads/gannhan_new/gannhan_new/data/resized/"
test_csv: ""
test_dir: ""
train_ratio: 0.85
hidden_units: 2048
epochs: 50

labels:
  - HG
  - HT
  - TR
  - CTH
  - BD
  - VH
  - CTQ
  - DQT
  - KS
  - CVN