train_csv: "D:/Dataset/scene_dataset/labels_normalized.csv"
train_dir: "D:/Dataset/scene_dataset/images/"
test_csv: ""
test_dir: ""
train_ratio: 0.85
hidden_units: 2048
epochs: 50

labels:
  - desert
  - mountains
  - sea
  - sunset
  - trees